services:
  sitepix:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      # Deixe a PORT com default local; o painel vai injetar de qualquer jeito
      PORT: ${PORT:-3000}
