services:
  sitepix:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      PUSHINPAY_TOKEN: ${PUSHINPAY_TOKEN}
